export const REQUEST_ALL_PRODUCT = "REQUEST_ALL_PRODUCT"
export const SUCCESS_ALL_PRODUCT = "SUCCESS_ALL_PRODUCT"
export const FAILED_ALL_PRODUCT = "FAILED_ALL_PRODUCT"

export const REQUEST_One_PRODUCT = "REQUEST_One_PRODUCT"
export const SUCCESS_One_PRODUCT = "SUCCESS_One_PRODUCT"
export const FAILED_One_PRODUCT = "FAILED_One_PRODUCT"

export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP"
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP"
export const FAILED_SIGN_UP = "FAILED_SIGN_UP"

export const REQUEST_LOG_IN = "REQUEST_LOG_IN"
export const SUCCESS_LOG_IN = "SUCCESS_LOG_IN"
export const FAILED_LOG_IN = "FAILED_LOG_IN"

export const PLUSE = "PLUSE"

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED"

export const USER_INFO_REQUEST = "USER_INFO_REQUEST"
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS"
export const USER_INFO_FAILED = "USER_INFO_FAILED"

export const CHANGE_INFO_REQUEST = "CHANGE_INFO_REQUEST"
export const CHANGE_INFO_SUCCESS = "CHANGE_INFO_SUCCESS"
export const CHANGE_INFO_FAILED = "CHANGE_INFO_FAILED"

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST"
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS"
export const ALL_ORDERS_FAILED = "ALL_ORDERS_FAILED"

export const ONE_ORDERS_REQUEST = "ONE_ORDERS_REQUEST"
export const ONE_ORDERS_SUCCESS = "ONE_ORDERS_SUCCESS"
export const ONE_ORDERS_FAILED = "ONE_ORDERS_FAILED"
